---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod

# TODO: `cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch`
# patches:
# - replicas.yaml
patches:
- target:
    kind: Deployment
    name: mywebapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5

configMapGenerator:
- name: mykustom-map
  behavior: replace
  env: config.properties
